name: PR

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

concurrency:
  # For PRs, use the ref (branch) in the concurrency group so that new pushes cancel any old runs.
  # For pushes to main, ideally we wouldn't set a concurrency group, but github actions doesn't
  # support conditional blocks of settings, so we use the SHA so the "group" is unique.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: .nvmrc

      - run: yarn --immutable

      - run: yarn build

      # This will fail on missing dist-file updates
      - name: Check for modified files
        uses: ecraig12345/beachball-actions/check-for-modified-files@336d3a84a5c452f5264803f4c62c6c34b4a51fbe # v2
        with:
          extraError: If files under "dist/" were changed, please run "yarn build" and commit the changes.
